PER_PAGE = 5
STYLE_LIST = [
    "`love`\n"
    "`friendship`\n"
    "`gratitude`\n"
    "`hope`\n"
    "`encouragement`\n"

    "`melancholy`\n"
    "`heartbreak`\n"
    "`nostalgia`\n"
    "`loneliness`\n"
    "`forgiveness`\n"

    "`funny`\n"
    "`absurd`\n"
    "`sarcastic`\n"
    "`parody`\n"
    "`dadjoke`\n"

    "`cringe`\n"
    "`chaotic`\n"
    "`random`\n"
    "`meme`\n"
    "`goofy`\n"

    "`roast`\n"
    "`savage`\n"
    "`mocking`\n"
    "`trash-talk`\n"
    "`sassy`\n"

    "`petty`\n"
    "`teasing`\n"
    "`grumpy`\n"
    "`vulgar`\n"
    "`rude`\n"

    "`unhinged`\n"
    "`chaos`\n"
    "`drunk`\n"
    "`angry`\n"
    "`nature`\n"

    "`forest`\n"
    "`ocean`\n"
    "`mountain`\n"
    "`rain`\n"
    "`storm`\n"

    "`flowers`\n"
    "`autumn`\n"
    "`winter`\n"
    "`spring`\n"
    "`summer`\n"

    "`fantasy`\n"
    "`magic`\n"
    "`dragon`\n"
    "`fairytale`\n"
    "`wizard`\n"

    "`mythology`\n"
    "`space`\n"
    "`cyberpunk`\n"
    "`steampunk`\n"
    "`robot`\n"

    "`alien`\n"
    "`future`\n"
    "`dark`\n"
    "`gothic`\n"
    "`mystery`\n"

    "`horror`\n"
    "`dream`\n"
    "`night`\n"
    "`moon`\n"
    "`stars`\n"

    "`haiku`\n"
    "`sonnet`\n"
    "`freeverse`\n"
    "`ballad`\n"
    "`limerick`\n"

    "`birthday`\n"
    "`christmas`\n"
    "`halloween`\n"
    "`valentine`\n"
    "`wedding`\n"

    "`graduation`\n"
    "`musical`\n"
    "`rap`\n"
    "`slam`\n"
    "`shakespeare`\n"

    "`medieval`\n"
    "`potato`\n"
    "`banana`\n"
    "`duck`\n"
    "`cat`\n"

    "`dog`\n"
    "`penguin`\n"
    "`pizza`\n"
    "`coffee`\n"
    "`cheese`\n"

    "`toilet`\n"
    "`sock`\n"
    "`bread`\n"
    "`rubberduck`\n"
    "`minecraft`\n"

    "`npc`\n"
    "`epic`\n"
    "`heroic`\n"
    "`villain`\n"
    "`pirate`\n"

    "`cowboy`\n"
    "`ninja`\n"
    "`detective`\n"
    "`king`\n"
    "`queen`\n"
]